### ISSUE TITLE
TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey

### ISSUE THREAD

**Issue by DennisSuitters** [farmOS/farmOS#558] opened 2022-08-26 11:21 UTC
**Describe the bug**
During the install process, after selecting which modules to install I get this:
````
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /farmOS/web/core/install.php?rewrite=ok&profile=farm&langcode=en&id=2&op=do_nojs&op=do
StatusText: OK
ResponseText: TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in openssl_pkey_get_details() (line 27 of /var/www/farmOS/web/modules/simple_oauth/src/Service/KeyGenerator.php).
````

**To Reproduce**
1. Go through the installation process

**Expected behavior**
Not this
````
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /farmOS/web/core/install.php?rewrite=ok&profile=farm&langcode=en&id=2&op=do_nojs&op=do
StatusText: OK
ResponseText: TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in openssl_pkey_get_details() (line 27 of /var/www/farmOS/web/modules/simple_oauth/src/Service/KeyGenerator.php).
````

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint with an Apache 2, PHP 8, MySQL (Forget which version)
 - Browser: Chrome
 - Version: 104.0.5112.101 (Official Build) (64-bit)

**Additional context**
The error is reporting an issue with SSL, I know for a fact it's not my system causing that, as I use SSL all the time, and have it OpenSSL setup for GitHub, and other software that require's it. I'm not using it for localhost development, and you shouldn't be forcing people to use it, or is that a Drupal requirement. Even so, they shouldn't be forcing it for localhost, it can be autodetectable, as that's what I do for my CMS.
Technically, all that's should need installing is the Database and credentials, and setting up an initial account, to me using Drupal is overkill.
I realised and appreciate that you guys are dedicated and engrossed with Drupal, but consider how much of the code you need to change, have you ever considered building something from scratch. I'm the sole developer of AuroraCMS, and I know that it's not that hard to build something from scratch. I'd be more than happy to discus this further if you do indeed have plans, or if you could direct me to a discussion that's already in motion.

**Comment by mstenta** [comment] 2022-08-26 11:28
Thanks for reporting this @DiemenDesign - I haven't experienced this before.

> `TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in openssl_pkey_get_details() (line 27 of /var/www/farmOS/web/modules/simple_oauth/src/Service/KeyGenerator.php).`
> ...
> The error is reporting an issue with SSL

This is not actually an issue with SSL.

When farmOS is installed, the `simple_oauth` module gets installed as a dependency (this enables OAuth2 access to the farmOS API endpoints). During installation of the `simple_oauth` module, it attempts to generate a public/private keypair in a `keys` directory for use in OAuth2 encryption. So something went wrong in your case when it was trying to generate those keys.

> OS: Linux Mint with an Apache 2, PHP 8, MySQL (Forget which version)

farmOS does not support PHP 8 (yet!). The required version is PHP 7.4 (as described here: https://farmos.org/hosting/install/#web-server). The issue for PHP 8 support is here if you are interested in following/helping (not much left to do!): https://www.drupal.org/project/farm/issues/3186530

I'm not sure if this is the cause of your issue, but perhaps it would be worth trying again on PHP 7.4.

Or, if you can use Docker that is the recommended approach to running farmOS: https://farmos.org/hosting/install/#farmos-in-docker

**Comment by mstenta** [comment] 2022-08-26 11:30
To be clear: SSL is not a requirement to use farmOS.

**Comment by mstenta** [comment] 2022-08-29 12:20
@DiemenDesign were you able to figure out what the cause of this issue was?

**Comment by DennisSuitters** [comment] 2022-08-29 12:36
Nope, but changing the PHP version so I could at least run farmOS, nuked some of the dependencies, I had to remove Apache2 and all of PHP/MySQL and reinstall them. I gave up, as my client's web development is more important. I can wait until farmOS works on PHP8. We're also in the middle of Lambing atm, so have been extra busy (as always at this time of year, lol).

My main reason for trying out farmOS was to be able to design our paddock layout. We're on a newish property, where the current fencing needs fixing, so I'm taking the opportunity to redo the fencing layout and set up the non-existent handling yards so each paddock can run the animals into the yard without letting them into other paddocks.

I had a look at FarmDeck, which works well, but it only handles Sheep and Cattle. I also need something to handle Goats, Birds (Geese, Ducks, Chickens and Guinea Fowl).

Thanks for checking in, it's often overlooked.

**Comment by mstenta** [comment] 2022-08-29 12:41
Cool sounds good! I'm going to close this issue for now, but feel free to reopen if it seems to be persistent.

If you want, feel free to do the 30-day trial of farmOS via Farmier: https://farmier.com/signup - you can map your paddocks there and then export them as KML to import into your own self-hosted instance later. That would at least give you the chance to start if you wanted to. :-)

**Closed as not planned by mstenta** 2022-08-29 12:41 UTC
Labels: bug
