### ISSUE TITLE
Grouping error: 7 ERROR: column "ss_log.timestamp" must appear in the GROUP BY clause or be used in an aggregate function

### ISSUE THREAD

**Issue by Skipper-is** [farmOS/farmOS#180] opened 2019-05-25 13:38 UTC
Getting the following error message:
`PDOException: SQLSTATE[42803]: Grouping error: 7 ERROR: column "ss_log.timestamp" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: SELECT ss_log.timestamp AS ss_logtimestamp, ss_log.id AS ss_... ^: SELECT ss_log.timestamp AS ss_logtimestamp, ss_log.id AS ss_logid, SUM(ss_fdffiv.field_farm_inventory_value_numerator / ss_fdffiv.field_farm_inventory_value_denominator) AS inventory FROM {log} ss_log INNER JOIN {field_data_field_farm_inventory} ss_fdffi ON ss_fdffi.entity_type = 'log' AND ss_fdffi.entity_id = ss_log.id AND ss_fdffi.deleted = 0 INNER JOIN {field_data_field_farm_inventory_asset} ss_fdffia ON ss_fdffia.entity_id = ss_fdffi.field_farm_inventory_value AND ss_fdffia.deleted = 0 INNER JOIN {field_data_field_farm_inventory_value} ss_fdffiv ON ss_fdffiv.entity_id = ss_fdffi.field_farm_inventory_value AND ss_fdffiv.deleted = 0 WHERE (ss_log.timestamp <= 1558788724) AND (ss_log.done = 1) AND (ss_fdffia.field_farm_inventory_asset_target_id = 3) ORDER BY ss_log.timestamp DESC, ss_log.id DESC LIMIT 1 OFFSET 0; Array ( ) in farm_inventory() (line 417 of /var/www/html/farmOS/profiles/farm/modules/farm/farm_inventory/farm_inventory.module).`

The process I went through to get this error were:
php7.1 (+the dependencies), running on PostGresql 10.8,

**Assets>Animals>Add Animal**
**Name:** "Ram"
**Species/Breed:** "Texel"

Everything else blank

**Save**

Says "Ram added", but animal list is empty, no animals found. 
If I click on the "Ram" of ram added, it takes me to the asset page (/farm/animal/ram), or rather, it should, but it gives me an error and the above error message appears in the log.

I tried the SQL query in PostGresql, on its own, and it gave the same result.

**Comment by mstenta** [comment] 2019-05-27 21:00
Thanks for the bug report @Skipper-is - I think this may be the same issue that was reported here: https://github.com/farmOS/farmOS/issues/167

I fixed it in the 7.x-1.x branch of farmOS by patching Drupal core (https://github.com/farmOS/farmOS/commit/d9b2eab174097a26cb826ec21a8a2089e336e1cd), using the patch from here: https://www.drupal.org/node/2057693

What version of farmOS are you using?  The patch is not included in 7.x-1.1, so if that's what you are using then maybe you just need to apply this patch.  Could you try that for me?  Are you familiar with applying patches?  If not, I'm happy to write up some quick instructions.

**Comment by mstenta** [comment] 2019-05-27 21:05
Short summary of what the issue is, and why I think this is the same: Drupal 7's PostgreSQL driver is currently adding fields to select queries whenever an `ORDER BY` is used, and this results in extra columns in the query that shouldn't be there.

In the query you posted above, it is selecting 3 fields:

`SELECT ss_log.timestamp AS ss_logtimestamp, ss_log.id AS ss_logid, SUM(ss_fdffiv.field_farm_inventory_value_numerator / ss_fdffiv.field_farm_inventory_value_denominator) AS inventory`

... but it should only be selecting 1:

`SELECT SUM(ss_fdffiv.field_farm_inventory_value_numerator / ss_fdffiv.field_farm_inventory_value_denominator) AS inventory`

And so, PostgreSQL is complaining that those two extra columns are not being properly included in a `GROUP BY` clause: `column "ss_log.timestamp" must appear in the GROUP BY clause or be used in an aggregate function`

So I'm pretty sure it's the same issue we fixed in #167. Let's hope! :-)

**Comment by Skipper-is** [comment] 2019-05-30 14:38
https://github.com/farmOS/farmOS/blob/7.x-1.x/drupal-org-core.make#L14 Appears to have closed the issue

**Comment by mstenta** [comment] 2019-06-19 13:29
@Skipper-is Did you confirm that this is still an issue? Or can we close this again?

**Comment by Skipper-is** [comment] 2019-07-03 18:28
I have just tried to create a new animal (with an inventory of 25), and I'm getting the same error. I can confirm that the patch is applied.

**Comment by mstenta** [comment] 2019-07-03 21:46
Thanks for reopening @Skipper-is. I am able to replicate this error. It is different than the one we encountered before in #167 - I just need to figure out how...

**Comment by mstenta** [comment] 2019-07-03 21:48
I think this is the issue (with a suggested solution): https://stackoverflow.com/questions/19601948/must-appear-in-the-group-by-clause-or-be-used-in-an-aggregate-function

> To workaround this issue, you must calculate the aggregate in a sub-query and then join it with itself to get the additional columns you'd need to show

**Closed as completed** 2019-07-04 02:29 UTC
Labels: bug, postgresql

**Comment by mstenta** [comment] 2019-07-04 02:31
OK I figured out why this was happening and pushed a fix for it: https://github.com/farmOS/farmOS/commit/dbbfd895ffde23c0920a4d4b5bab37449a6557db
