### ISSUE TITLE
Geolocate button not working

### ISSUE THREAD

**Issue by thedude459** [farmOS/farmOS#9] opened 2016-08-07 23:12 UTC
When I try to add an area and I hit the geolocate button nothing happens.

**Comment by mstenta** [comment] 2016-08-08 13:03
Thanks for the bug report @thedude459 - it does indeed look like the geolocation button isn't working. I'll see what I can find...

One thing to note: Google has deprecated geolocation on non-secure sources recently (https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins) - which means it will only work on HTTPS (SSL) sites.

**Comment by mstenta** [comment] 2016-08-08 13:04
(regarding the non-secure sources... I am also seeing that it's not working on Farmier-hosted sites, which use HTTPS... so definitely a bug...)

**Comment by mstenta** [comment] 2016-08-08 13:16
Confirmed that it's also not working in Firefox.

**Comment by mstenta** [comment] 2016-08-08 13:20
It seems that the official example is broken too: http://openlayers.org/en/latest/examples/geolocation.html

So this looks to be a bug in the Openlayers library itself - not farmOS.

I will submit an issue to the upstream repository...

**Comment by mstenta** [comment] 2016-08-08 13:23
https://github.com/openlayers/ol3/issues/5700

**Comment by mstenta** [comment] 2016-08-08 13:33
This might be an issue with Google's APIs, actually... even their own examples are failing currently:

https://developers.google.com/maps/documentation/javascript/examples/map-geolocation

**Comment by mstenta** [comment] 2016-08-08 13:45
@thedude459 What operating system do you use?

I just found that it works on my wife's computer (Windows), but not on mine (Ubuntu).

**Comment by thedude459** [comment] 2016-08-08 13:55
It is running in a docker with a baseimage of ubuntu.

**Comment by mstenta** [comment] 2016-08-08 13:56
@thedude459 Thanks - What operating system are you using to access it with? And what browser?

**Comment by thedude459** [comment] 2016-08-08 13:56
I am using windows 10 and chrome.

**Comment by mstenta** [comment] 2016-08-08 13:59
Hmm ok - your issue may actually be due to the fact that Chrome requires sites that are using Geolocation to be served over HTTPS. If you are hosting locally, I doubt that you went to the trouble of setting up an SSL certificate, right?

Does it work for you in Firefox? Or Internet Explorer / Edge?

**Comment by thedude459** [comment] 2016-08-08 14:01
Works in IE but I am getting a "You are not authorized to access this page." on the right side of the screen.

**Comment by mstenta** [comment] 2016-08-08 14:03
@thedude459 Ok thanks - that confirms that it's a Chrome issue, specifically when trying to use Geolocation on an insecure site (non-HTTPS).

The "not authorized to access" message is because you are not logged in on the IE browser. Go to http://[your-docker-ip]/user to see the login screen.

**Comment by thedude459** [comment] 2016-08-08 14:24
Is there a reason that happens in IE but not chrome? The not authorized issue?

**Comment by mstenta** [comment] 2016-08-08 14:26
It's just because you originally installed farmOS from Chrome, so it saved your login session and kept you logged in. If you go to http://[your-docker-ip/user/logout in Chrome it will log you out and you will see the same thing that you see in IE.

**Comment by mstenta** [comment] 2016-08-08 14:27
I'm going to close this because it's not specifically a farmOS issue - but I added a new issue to the farmOS.org documentation project so that we can describe this HTTPS requirement to people who are getting started for the first time: https://github.com/farmOS/farmOS.org/issues/13

**Closed as completed by mstenta** 2016-08-08 14:27 UTC
