### ISSUE TITLE
SQL query fails on fresh install

### ISSUE THREAD

**Issue by jkelsh** [farmOS/farmOS#167] opened 2019-04-27 00:48 UTC
I posted this in the drupal queue but it was detected as spam, so am posting here.

Apache 2.4.18
PHP 7.0.33
PostgreSQL 9.5.16
FarmOS 1.1

On a fresh install, create an area and try to view that area, the attached query fails with error "subquery must return only one column at character 157"

[farmos.sql.txt](https://github.com/farmOS/farmOS/files/3123355/farmos.sql.txt)

**Comment by mstenta** [comment] 2019-04-29 14:53
I just tried replicating this using the PostGIS Docker container configuration that is in the farmOS docker subfolder: https://github.com/farmOS/farmOS/blob/7.x-1.x/docker/docker-compose.override.postgis.yml

Steps I took:

1. Create new directory `farmOS-pgsql`
2. Copy the `docker-compose.development.yml` file from the repo and rename it to `docker-compose.yml`.
3. Copy the `docker-compose.override.postgis.yml` file from the repo and rename it to `docker-compose.override.yml`.
4. Run `sudo docker-compose up`
5. Go to `http://localhost` and install farmOS.
6. Click "Add Area" from the farmOS dashboard.
7. Draw a new area on the map, make it a "Field" type, and save.
8. Go to "Areas" and click on the new area in the list.

I did not encounter any error.

Are those the same steps you took?  (Maybe without the Docker steps 1-5?)

I did copy and paste the query you attached into PGAdmin, and I DID receive the same error. So that query is not correct. Where did you get it from?

I'm closing this because I couldn't reproduce, but let's keep debugging and if we discover an issue with farmOS we can reopen to fix it.

**Comment by mstenta** [comment] 2019-04-29 14:54
> I did copy and paste the query you attached into PGAdmin, and I DID receive the same error. So that query is not correct. Where did you get it from?

If farmOS produced this query, then perhaps there is a bug. It did not happen in my test, though, so I'm curious where that query came from.

**Comment by jkelsh** [comment] 2019-04-30 11:31
I can no longer replicate the exact issue I was experiencing previously (so what I was seeing, a blank page, must've been unrelated). 

> If farmOS produced this query, then perhaps there is a bug. It did not happen in my test, though, so I'm curious where that query came from.

The database error is never displayed through the web interface but is logged in the postgres log. I'm (still) seeing it specifically when I view the asset list (which incidentally shows no assets, even after creating some).

**Comment by mstenta** [comment] 2019-04-30 12:56
> The database error is never displayed through the web interface but is logged in the postgres log. I'm (still) seeing it specifically when I view the asset list (which incidentally shows no assets, even after creating some).

Thanks! That helps - I'm seeing that as well. And the assets lists are empty. I think I know where the issue is... will see if I can get to the bottom of it...

**Comment by mstenta** [comment] 2019-04-30 12:57
Also, looks like your post to drupal.org did work, in fact: https://www.drupal.org/project/farm/issues/3049411

I will close that as a duplicate of this.

**Comment by mstenta** [comment] 2019-04-30 13:19
OK I'm starting to see where the issue is... it's a deep one.

The query in question is being generated by the `farm_movement_asset_movement_query()` function, which is for building a query to find movement logs of a specific asset (for showing the asset's location in the asset lists, in this case): https://github.com/farmOS/farmOS/blob/9dc85dbc8f1d538ee98e9c397f412e21644ef744/modules/farm/farm_movement/farm_movement.location.inc#L456

That function ultimately starts with the output of `farm_log_query()`: https://github.com/farmOS/farmOS/blob/9dc85dbc8f1d538ee98e9c397f412e21644ef744/modules/farm/farm_log/farm_log.module#L691

`farm_log_query()` adds some default `ORDER BY` clauses to the query, so that logs are sorted by timestamp and log ID:

```
  // Order by timestamp and then log id, descending.
  $query->orderBy('ss_log.timestamp', 'DESC');
  $query->orderBy('ss_log.id', 'DESC');
```

In MySQL/MariaDB, using the `orderBy()` method works as expected. It adds an `ORDER BY` clause to the query.

In PostgreSQL, apparently, it ALSO adds fields to the query.  This is why we are seeing "`subquery must return only one column`".

It looks like this is an issue with the Drupal PostgreSQL database driver itself.  There is an open issue for it in the Drupal core issue queue: https://www.drupal.org/project/drupal/issues/2057693

That issue is marked as "Needs Review" for inclusion in Drupal 8. farmOS, however, is still on Drupal 7.

So we may need to find a workaround...

**Comment by mstenta** [comment] 2019-04-30 13:55
I looked at the Drupal 8 patch and it's pretty simple. So I backported it to Drupal 7: https://www.drupal.org/project/drupal/issues/2057693#comment-13088470

I can include this patch in farmOS, moving forward. I will prepare a commit for that.

In the meantime, I'd love to have you test it out, if you can @jkelsh.

To apply the patch, follow these steps:

1. Download the patch file to the farmOS web root: http://www.drupal.org/files/issues/2019-04-30/2057693-D7-42.patch
2. Run the following command: `patch -p1 < 2057693-D7-42.patch`
3. If you don't see any errors, try loading your assets list page again and see if the issue is fixed.

**Comment by mstenta** [comment] 2019-04-30 14:00
I pushed a tentative fix commit to my fork: https://github.com/mstenta/farmOS/commit/eddff25e1a1b3be8afbbca4ba4a6b52737385049

I will merge this in once we have confirmation that it fixes the issue.

**Comment by jkelsh** [comment] 2019-05-01 09:38
> In the meantime, I'd love to have you test it out, if you can @jkelsh.

Tested and can confirm this fixes the issue, asset page returns to functional.

**Comment by mstenta** [comment] 2019-05-01 13:00
Great! Thanks @jkelsh !

I merged in the patch commit, so it will be included in the next release of farmOS.

Thanks again for reporting and helping to fix this!

**Closed as completed by mstenta** 2019-05-01 13:00 UTC
