### ISSUE TITLE
Bulk actions using different date format

### ISSUE THREAD

**Issue by botlfarm** [farmOS/farmOS#509] opened 2022-03-14 18:09 UTC
When selecting multiple assets from a list and applying bulk actions (for example at the bottom action-> group assets) the simple form does not have a place for time. It also is using the older style date picker selecting year, month, and day separately as apposed to selecting from a calendar. For consistency it would be nice to see the date/time selection to be the same across all input locations.

**Comment by Yash621** [comment] 2022-03-22 15:30
@botlfarm can i work on  this ?

**Comment by botlfarm** [comment] 2022-03-22 17:25
I don't see why not. I'm sure the farmOS team would appreciate it.

**Comment by paul121** [comment] 2022-03-22 17:39
Yes @Yash621 that would be great! Let us know if you have any questions.

There are at least three types of date selectors I can think of... `datetime`, `date` and `datelist`. I think @botlfarm is referring to the `date` selector which includes the calendar (although this might depend on the user's browser implementation of the native date element).

Re: date + time, we've discussed creating a custom form element that would allow optionally adding a time in addition to the date. This would be quite a bit more work, I might focus on just standardizing the date input for now.

Most of our bulk actions are in farmOS core (this repo) but note that some of the log actions (clone log, reschedule log) are provided by a separate `log` module and will need issues + merge requests created over here: https://www.drupal.org/project/log

**Comment by mstenta** [comment] 2022-03-22 18:49
> Re: date + time, we've discussed creating a custom form element that would allow optionally adding a time in addition to the date. This would be quite a bit more work, I might focus on just standardizing the date input for now.

Agreed. We should approach this in two steps:

1. Change the existing date selection widget from dropdowns to the standard calendar popup we use elsewhere.
2. Add the ability to *optionally* specify time.

Time needs to be optional, because if it's not then everyone who doesn't care about time all of a sudden needs to, which adds cognitive overhead to what would be a simple decision. Time is not necessary all the time. If we make it required before we make it optional then it will be a step backwards from a UX perspective IMO.

I think the second step should be a standalone issue separate from this one, because it is bigger.

**Comment by mstenta** [comment] 2022-03-22 18:50
> Change the existing date selection widget from dropdowns to the standard calendar popup we use elsewhere.

The first step is to make a list of all the places this needs to be changed. @botlfarm do you want to start this? Then we can help point @Yash621 towards the relevant code for each.

**Comment by botlfarm** [comment] 2022-03-22 19:28
> Time needs to be optional

I completely agree @mstenta . Time recording is useless for me in 95% of my logs. I guess I was initially looking at this as a consistency issue across farmOS. Creating a log currently requires a time so I thought cloning a log should also require the same for consistency. I also thought this is how it was in1.x but after double checking it was not. 

I'm learning this probably should have been a forum post first to discuss before creating an issue. My bad!

What caught my attention and my main point was the date selection process.  So far the only places I have seen the date selection as the old style and not the calendar popup is in the bulk actions. For logs this is `clone` and `reschedule`. For assets this is `move asset` and `group asset`. I will keep an eye out for more.

**Comment by mstenta** [comment] 2022-03-22 21:24
> looking at this as a consistency issue across farmOS. Creating a log currently requires a time so I thought cloning a log should also require the same for consistency.

Agreed 100% @botlfarm! If anything, the bulk actions forms are too general, and the log forms are too specific! So both could be improved by implementing a shared widget/element that makes time selection optional.

> I'm learning this probably should have been a forum post first to discuss before creating an issue. My bad!

No worries - we're all learning what works best - me included. I still go back and forth on what's best - no hard and fast rules. Maybe this needs a forum topic of it's own ha! :sweat_smile: 

> What caught my attention and my main point was the date selection process. So far the only places I have seen the date selection as the old style and not the calendar popup is in the bulk actions.

Yea I think this is a good place to start! I think the reason that the bulk actions use the "old style" is somewhat historical. We ported the [Log](https://www.drupal.org/project/log/) module to Drupal 8/9 first, before starting farmOS. And so it was just a straight port, maintaining the old form widgets too. Then, we copied/modified that action code for the actions in farmOS.

> For logs this is `clone` and `reschedule`. For assets this is `move asset` and `group asset`. I will keep an eye out for more.

Great! Thanks!!

**Comment by mstenta** [comment] 2022-03-22 21:27
@Yash621 here is where those forms are (in the Log module repository and the farmOS repository):

- `clone` abd `reschedule` Log actions both extend from the `LogActionFormBase` class. Here is the relevant code that defines the date field: https://git.drupalcode.org/project/log/-/blob/2.x/src/Form/LogActionFormBase.php#L109
- `move asset`: https://github.com/farmOS/farmOS/blob/8a562d673e59e8fd405bc2bcc40a257e649ff4d5/modules/core/location/src/Form/AssetMoveActionForm.php#L138
- `group asset`: https://github.com/farmOS/farmOS/blob/8a562d673e59e8fd405bc2bcc40a257e649ff4d5/modules/asset/group/src/Form/AssetGroupActionForm.php#L138

Notice how all three of those use the following field widget type:

```
'#type' => 'datelist',
```

As @paul121 stated above:

> There are at least three types of date selectors I can think of... `datetime`, `date` and `datelist`.

I think we want to just change the `#type` to `date`. But you may also need to modify some of the other form element properties along with that.

Here is the api.drupal.org documentation for each type:

- `date`: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21Element%21Date.php/class/Date/9.3.x
- `datelist`: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Datetime%21Element%21Datelist.php/class/Datelist/9.3.x
- `datetime`: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Datetime%21Element%21Datetime.php/class/Datetime/9.3.x

**Comment by mstenta** [comment] 2022-03-22 21:28
@Yash621 PS - here is documentation for getting set up with a local development environment: https://farmos.org/development/environment/

Good luck and feel free to ping us here or in [chat](https://app.element.io/#/room/#farmOS:matrix.org) if you have questions!

**Comment by Yash621** [comment] 2022-03-23 20:25
@mstenta @paul121 thank you so much for the guidance, I will surely reach out if I face any problems :)

**Comment by Yash621** [comment] 2022-03-24 08:25
@mstenta @paul121 Unfortunately my college is taking exams on very short notice, will it be okay if I get back onto it after some time ? I am extremely sorry for this .

**Comment by mstenta** [comment] 2022-03-24 12:59
@Yash621 of course! There's no deadline for volunteering. We appreciate any help you can provide! :-)

Good luck on your exams!

**Comment by Yash621** [comment] 2022-03-24 15:06
thanks @mstenta really appreciate it.

**Comment by erlarese** [comment] 2023-01-17 03:37
Hello, I'm not sure if @Yash621 is still interested in working on this, it looks like the last update was about a year ago.

I figured I would take a pass at this as my first defect, I created the changes suggested by @mstenta in https://github.com/farmOS/farmOS/issues/509#issuecomment-1075661144 and I created this branch: https://github.com/farmOS/farmOS/compare/2.x...erlarese:farmOS:erlarese_509?expand=1 -- I was able to test this locally and it seems to work, here is an example screenshot of the changes in the "move asset" panel:

![image](https://user-images.githubusercontent.com/4520557/212804427-2a8f1a6c-a7c6-459a-8699-3e83db15beba.png)

Does this seem like what we want?  Should I create a PR for this?  Is there anything else I should be looking at to include?  Thanks !

**Comment by mstenta** [comment] 2023-01-20 13:36
Thanks @erlarese! This looks good to me! Please do create a PR when you have a chance. I think that's a good next step.

I think I would like to make a similar change in the Log module (separate repo: https://www.drupal.org/project/log) at the same time, so that we maintain consistency across all the bulk action forms in farmOS. If you start a PR for farmOS, I can make the same changes in Log, and then merge them both at the same time so they can be in the next farmOS release.

**Comment by erlarese** [comment] 2023-01-20 18:27
Thanks @mstenta, that sounds good.  I created PR https://github.com/farmOS/farmOS/pull/630.

**Comment by paul121** [comment] 2023-01-31 20:52
I've left a review on the PR but wanted to mention it here, and expand on thought 4...: https://github.com/farmOS/farmOS/pull/630#pullrequestreview-1277984088

Looking into all of this again... I'm just curious if we could support date and time inputs in these forms. If so then the `datetime` element which uses separate HTML5 `date` and `time` inputs would be the best option. @botlfarm first seemed to request time but I'm just now seeing he said this it is useless 95% of the time... :-)

> Time needs to be optional, because if it's not then everyone who doesn't care about time all of a sudden needs to, which adds cognitive overhead to what would be a simple decision. Time is not necessary all the time. If we make it required before we make it optional then it will be a step backwards from a UX perspective IMO.

@mstenta there is some cognitive overload, yes.  But with HTML5 `time` input & a sensible default value... is this sufficient for "optional" time input? Learning to ignore the `time` input after a few uses of these forms seems to be easier than manually editing a log to add a time when that is needed. I'm of the opinion that this serves a broader range of use-cases, at the risk of cognitive overload for newer users.

Also interesting.... in the long run I think the HTML5 `datetime-local` input would be ideal. There is good browser support: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local however it doesn't seem that Drupal supports this yet: https://www.drupal.org/project/drupal/issues/1496652

**Comment by mstenta** [comment] 2023-02-01 21:20
> @mstenta there is some cognitive overload, yes. But with HTML5 time input & a sensible default value... is this sufficient for "optional" time input? Learning to ignore the time input after a few uses of these forms seems to be easier than manually editing a log to add a time when that is needed. I'm of the opinion that this serves a broader range of use-cases, at the risk of cognitive overload for newer users.

That makes sense to me, and a default of midnight is the "implicit convention" so if we can easily do that, great!

**Comment by paul121** [comment] 2023-02-01 22:57
> and a default of midnight is the "implicit convention" so if we can easily do that, great!

Yes this should be possible. I actually tried this with the [`DruaplDateTime::setDefaultDateTime()` ](
https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Datetime%21DateTimePlus.php/function/DateTimePlus%3A%3AsetDefaultDateTime/10) helper method. It set the default time to 12:00 noon in the HTML `time` input and I confirmed it submitted the correct time when only selecting a different `date`.

It is interesting their reason for using 12:00:

> The default time for a date without time can be anything, so long as it is consistently applied. If we use noon, dates in most timezones will have the same value for in both the local timezone and UTC.

Not really suggesting we change. I don't think we need to worry about comparability of dates across timezones within a single instance. But as we do more aggregations this could be kinda relevant.

**Comment by mstenta** [comment] 2023-02-02 14:42
> It is interesting their reason for using 12:00

That is interesting.

Maybe we should take this one step at a time - feels like the scope is growing if we also want to standardize on "noon" instead of "midnight" - and I'd like to wrap my head around the timezone considerations a bit with that. The most important thing is consistency - and IIRC there is code sprinkled throughout farmOS core and contrib that uses logic equivalent to `strtotime(date('Y-m-d'))` (aka midnight) for saving timestamps where a time isn't specified. I'm not excited to comb through and change all those. :sweat_smile:

**Comment by mstenta** [comment] 2023-02-05 13:39
Closed by #630, #635, and https://www.drupal.org/project/log/issues/3336721.

**Closed as completed** 2023-02-05 13:38 UTC
Labels: bug
