### ISSUE TITLE
Cannot create area taxonomy_term via API

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS#156] opened 2019-03-30 19:00 UTC
The server returns an HTTP 406 error when creating a taxonomy_term of vocabulary farm_areas

Taxonomy terms of vocabulary farm_crops can be created with the following request data POST to /taxonomy_term: (from [here](https://github.com/paul121/farmOS.py/blob/33a45a2532a6c9598f0ba1cb8badbb067c445410/tests/functional/test_term.py#L4-L10) )
`test_term = {
    'name':'API Crop Test ',
    'vocabulary': {
        'id':'7' #this id is dynamically filled in with the VID for the farm_crops vocabulary
        'resource':'taxonomy_vocabulary'
    }
}`
returns HTTP 201

Attempting to POST to taxonomy_term OR taxonomy_term.json/bundle=farm_areas with request data:
`{'name': 'Testing area', 'description': 'Created via farmOS.py testing script', 'area_type': 'field', 'vocabulary': {'id': '3', 'resource': 'taxonomy_vocabulary'}}`

returns a 406 response

**Comment by paul121** [comment] 2019-03-30 19:02
Also, this is not fully documented in [farmOS.org](https://farmos.org/development/api/#creating-records)

There is a section for Creating Areas, but no example usage - assuming area creation behaves like taxonomy_term creation, but I could be wrong!

**Comment by mstenta** [comment] 2019-03-30 19:05
@paul121 Are you posting to a farmOS running locally in Docker? I fixed an issue with creating taxonomy terms recently (before releasing farmOS 1.0). I wonder if you are using an older version?

**Comment by mstenta** [comment] 2019-03-30 19:06
Ooh wait... no sorry this is a different issue.

It's because of the `description` field. Take that out and it will work.

Here is the bug report for that in farmOS: https://www.drupal.org/project/farm/issues/3043569

**Comment by mstenta** [comment] 2019-03-30 19:07
Gonna close this as a duplicate of that one...

**Closed as completed by mstenta** 2019-03-30 19:07 UTC
Labels: bug, duplicate

**Comment by paul121** [comment] 2019-03-30 19:10
Great!! Fixed. Is there a place to see where these kind of errors are logged in the farmOS instance? I checked the logs on my docker instance, but didn't find anything useful.

**Comment by mstenta** [comment] 2019-03-30 19:13
I'm not sure if the 406 errors are logged... that's a good question. Take a look in /admin/reports/dblog (that's the internal Drupal watchdog log).

The 406 response itself should be accompanied by a brief description of what went wrong. I think in this case it will say something like "`field_farm_description doesn't exist`".
