### ISSUE TITLE
The KML file cannot be imported

### ISSUE THREAD

**Issue by JoceFoo** [farmOS/farmOS#690] opened 2023-06-17 10:09 UTC
**Describe the bug**
1.     Clicks “Administration” in the side bar.
2.     Clicks “Import”
3.     Clicks “KML Import”
4.     Input KML file=sample.kml, Default land type=Landmark
![Picture1](https://github.com/farmOS/farmOS/assets/78674605/ab6b5300-1869-4531-b9e1-66f454326516)

**Comment by mstenta** [comment] 2023-06-17 12:45
@JoceFoo are you self-hosting? Have you configured farmOS to allow for file uploads? Are you able to upload files to assets/logs? If not, then the KML upload will fail too.

Please see https://farmos.org/hosting/install/#file-uploads - or search the farmOS forum for similar posts because others have encountered this before and fixed it themselves once they correctly configured file uploads.

I'm going to close this with that assumption, but feel free to reopen if you confirmed that you are able to upload files in other places. If that is the case, please also provide the KML file that you are testing with.

**Closed as not planned by mstenta** 2023-06-17 12:45 UTC
Labels: bug
