### ISSUE TITLE
Administration Content error

### ISSUE THREAD

**Issue by LunarDerrick** [farmOS/farmOS#696] opened 2023-06-21 05:28 UTC
Hi, I noticed that accessing Administration then Content will generate an error message regarding Drupal installation. It is not affecting other functions, so I believe it may be a catch statement that is not handled properly. I suggest to remove that to prevent confusion to other users.

**Comment by mstenta** [comment] 2023-06-21 12:10
@LunarDerrick thank you for contributing reports of the bugs/observations you have been encountering with farmOS (including your other recent issues: #693, #694, #695).

In the future, please use the "Bug report" template that is provided (screenshot below) when creating issues and include more detailed information about your environment and steps to reproduce. This makes it easier for others to determine if there is actually a bug with farmOS or not.

![Screenshot from 2023-06-21 07-59-48](https://github.com/farmOS/farmOS/assets/95381/87fca505-b7c9-4ab1-a0e6-86240004ac1c)

I am unable to replicate this issue myself, if I understand what you're describing correctly. Here is a screenshot of /admin/content on a working farmOS instance:

![Screenshot from 2023-06-21 08-07-57](https://github.com/farmOS/farmOS/assets/95381/b4e6d1ca-ea40-4b46-8dc1-6040c2d7d2d6)

It's worth noting that this page is hidden to most farmOS users. It is provided by Drupal, but not used in farmOS, because we do not use the `node` entity type.

I'm going to close this issue, but if you have additional information to provide about the error message please feel free to add it to the comments.

**Closed as not planned by mstenta** 2023-06-21 12:10 UTC
