### ISSUE TITLE
Export KML does not generate any file

### ISSUE THREAD

**Issue by LunarDerrick** [farmOS/farmOS#695] opened 2023-06-21 05:26 UTC
Hi, I noticed I can only generate .csv file, but not .kml file. This happens whenever I choose the "Export KML" action, I recommend enable selective generate .csv file as well because it is the current working solution.

**Comment by wotnak** [comment] 2023-06-21 11:41
Might be a duplicate of https://github.com/farmOS/farmOS/issues/688.

Do the assets, for which you are trying to export .kml file, have assigned geometry? Exporting KML currently isn't supported for assets without defined geometry. When trying to export KML for assets without geometry, a warning message should be displayed.
![image](https://github.com/farmOS/farmOS/assets/52507690/8ea242d2-b1e2-45b1-97e0-0c974618e7b3)

**Closed as completed** 2023-06-22 03:33 UTC
