### ISSUE TITLE
Areas not being displayed

### ISSUE THREAD

**Issue by daverclarke** [farmOS/farmOS#33] opened 2017-05-16 12:02 UTC
Using containers from the docker-compose.yml on 7.x-1.x branch at commit 5073592.

When I marked out the areas as per the attached screenshot I figured I would see some different things. When I scroll in enough I can see the property as a grey box, but that is all.  Is this the expected behavior

It shows up the same on a chrome book and via Chrome 58.0.3029.96

First is the overview of all

![2017-05-16 21-56-06](https://cloud.githubusercontent.com/assets/6365793/26104835/ead3b2e8-3a82-11e7-9881-92db6f2df518.png)

Second is a zoom on the paddocks. Top paddock, bottom paddock and orchard are all in the view. All boxes are selected in the layers menu except soil samples.

![paddock](https://cloud.githubusercontent.com/assets/6365793/26104905/33883f72-3a83-11e7-99bb-7213622211a2.png)

**Comment by mstenta** [comment] 2017-05-16 12:26
Hi @daverclarke,

When areas have both a "geometry" (drawn via the map, or imported via WKT/KML) and an "area type" (selected via dropdown), they should show up on the map, color-coded by area type (ie: Property is purple, Field is yellow, Paddock is green, etc). If you aren't seeing that behavior, then something's not working...

I assume your areas have geometries?  I can't tell that from your screenshots, but you did say you "marked out the areas" and that you "can see the property as a grey box", so that suggests they do. Where do you see the "grey box"? When you are editing/drawing an area? (That would make sense - when you are adding an area, all other area geometries are shown in light grey as a guide so you know where you're drawing should be in relation to them - I assume that's what you're seeing.)

Can you paste one of your area's geometries?  The WKT code will be visible in a text box below the map when you click the "Edit" tab on one of your areas.  Maybe something is not working with the geometry.  I can test it in my farmOS to see.

Thanks for the detailed bug report.

One question: you mentioned that you are using the 7.x-1.x branch at commit https://github.com/farmOS/farmOS/commit/5073592aac4d9f2f0f5d1c776255a6deadcd2d8d ... Did you build farmOS yourself via Drush?  Or did you download a packaged copy from drupal.org?

And more importantly: WHEN did you build/download? The reason I ask is I pushed a bunch of changes to a lot of the farmOS modules and distribution repos last night, including that commit.  So I want to make sure that you actually have a fully-functioning copy.  It's a bit risky to use the 7.x-1.x dev version because all the modules are in different repos, so you need to make sure that all of them are up-to-date as well (this is going to change in the beta14 release - I am going to merge them together to make things like that easier).  In general, I always recommend using the latest tagged release (in this case 7.x-1.0-beta12) packaged on drupal.org: drupal.org/project/farm (unless you are very familiar with all the moving parts) - I always make sure those packaged copies are stable (at least in terms of all the modules working together properly).  If you already have a bunch of data in your site, though, you probably shouldn't downgrade.  Maybe everything will work fine.  I am going to be releasing beta13 soon, so you should upgrade to that when I do, and then wait for the beta14 before upgrading again - that would be my recommendation anyway.  I don't want you to hit any bugs and get frustrated. :-)

All that said, I don't think this mapping issue is a result of the upgrades... I didn't change much with the mapping stuff... so this might be something else.  Let's keep digging and see if we can figure it out without touching any of the code yet...

**Comment by daverclarke** [comment] 2017-05-17 06:24
Hi @mstenta

This is a build by cloning the repository and running docker-compose up.  I've re-pulled the docker image and rebuilt the docker to see if it would change anything, but I'm still getting the same result.

```
[farmOS] docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
farmos/farmos                    7.x-1.x             20c7493aa7f5        7 days ago          542MB

```

I started this about a week ago, so it's fairly fresh.

I can see the area when I'm drawing, but a lot of them don't show up at all after that, including in the edit section.  The following polygon is tagged as a "paddock" in the type and isn't showing up on the map.

![polygon](https://cloud.githubusercontent.com/assets/6365793/26140970/e62cae1c-3b1c-11e7-9030-ba8349f3a77c.png)

**Comment by mstenta** [comment] 2017-05-17 10:43
@daverclarke - Those coordinates in the WKT <code>POLYGON(...)</code> do not appear to be correct. Notice how the first point has a longitude of 895.74... - that is not valid, it must be between -180 and 180.

How did you create that? Simply by drawing in the map? Or did you import it from a KML file? If you imported KML, it could be that the KML is not using the WGS84 projection.

If simply drawing on the map gave you those points - then something else must be happening. I've never experienced that before. Did you change any of your Openlayers module map settings? It seems that a different projection is being used for some reason, and that is resulting in invalid WKT.

Someone else reported the same issue previously, when they were importing KML - take a look and see if maybe this sounds like the same issue: https://www.drupal.org/node/2811733

**Comment by mstenta** [comment] 2017-05-17 10:54
PS: The Docker image currently builds the latest 7.x-1.x version of farmOS, so there is a chance that it's less stable than the packaged download. This will also change with the next release, because I'll start creating tagged Docker images as well (the Docker image was added after the most recent release, so I couldn't build an image off of the tagged version). In future versions, you will be able to use Docker images like <code>farmos/farmos:7.x-1.0-beta13</code> instead of <code>farmos/farmos:7.x-1.x</code>, so you can be sure that they are stable.

I wouldn't worry to much about it for now... it sounds like your version is probably fine. Aside from this mapping issue (which I think is unrelated to the version).

When the next tagged release is available, I would recommend moving to that (instead of using the 7.x-1.x). However, I want to double check that that is possible. I created a separate issue: https://github.com/farmOS/farmOS/issues/34 - please follow that issue and I'll post any details you may need to know.

**Comment by mstenta** [comment] 2017-05-17 11:28
@daverclarke Oh actually... (regarding Docker)... did you use the docker-compose.yml file to set up your two Docker containers? Or did you just manually set up the containers using the farmos/farmos:7.x-1.x image?

If you manually set them up, then you actually are using the latest tagged release (7.x-1.0-beta12). If you used docker-compose.yml, then you are using the dev branch (7.x-1.x). I'm refreshing on how all that is set up, and I just remembered that by default the FARMOS_DEV environment variable is set to "false" in the Docker image - but that gets overridden to "true" when using the docker-compose.yml. Anyway - that's unrelated to this specific issue, but I thought it was worth mentioning... I'll post more information in #34

**Comment by daverclarke** [comment] 2017-05-17 11:46
@mstenta I used the docker-compose.yml, so it's 7.x-1.x, not the beta tagged release. I'll try doing a build with my current configs.

I did the drawing with the polygon selection tool. I'll have a look at recreating each of them with the new updates.

**Comment by mstenta** [comment] 2017-05-17 12:04
@daverclarke Hmm very strange - I'm not sure why the polygon drawing tool would end up giving you incorrect coordinates.

I don't think updating your code will change anything... nothing has changed in the way the maps work since the latest release.

One thing we can try: can you paste a link to the exact point you are trying to map in Google Maps? Then I can see exactly where you are working, and try drawing some shapes myself in my farmOS to see what the lat/lon points look like for me. I wouldn't expect them to be different, but maybe there is actually a bug in specific areas of the globe??

**Comment by mstenta** [comment] 2017-05-17 14:24
@daverclarke Also note: simply updating the Docker image and recreating the container will NOT rebuild the farmOS codebase itself, because the codebase is mounted in a volume under the <code>.data/www</code> directory.

If you want to rebuild the farmOS codebase, delete the <code>.data/www/profiles/farm/farm.info</code> file, and then recreate the container. It will automatically detect that, backup your <code>sites</code> folder, rebuild the codebase (updating all modules to the latest commits), and then restore the <code>sites</code> folder. Please backup your <code>.data</code> folder first, though! Just to be safe... the easiest way to do that is to create a tar.gz archive of it: <code>sudo tar -czf data.tar.gz .data</code>.

I plan to document all this stuff a little better, to make it easier to use docker for both use cases: 1) local development, and 2) local farmOS hosting. Here is a new issue for that documentation if you want to follow along: https://github.com/farmOS/farmOS.org/issues/20

**Comment by daverclarke** [comment] 2017-05-18 09:41
@mstenta thanks for the info. I've drawn it in a farmier hosted instance and it draws fine.

The area I'm trying to work with is:

POLYGON ((175.7440772652626 -38.92325711760042, 175.7445278763771 -38.92306096499826, 175.7438144087791 -38.92194664098859, 175.7431545853615 -38.92249754493356, 175.7440772652626 -38.92325711760042))

When I paste that in, it displays correctly.  Must be something to do with the selection mechanism.

**Comment by mstenta** [comment] 2017-05-18 14:16
@daverclarke Very strange! You've perked my debugging interests! So when you draw a shape in farmOS on Farmier hosting it works, but when you draw a shape in your own local hosting it doesn't? That's bizarre - they should be the same. I wonder what is causing the difference.

I'll ponder that a bit today and see if anything comes to mind. I might ask you to try some things, if you don't mind. I'm really curious why that's happening.

**Comment by mstenta** [comment] 2017-05-18 14:25
Ah ha! I was able to replicate this myself in my own local Docker instance of farmOS. It seems to be happening if I draw a polygon in southeast Australia, but not if I draw polygons in northeast United States. And it does NOT happen on Farmier-hosted sites.

This gives me something to work with... I will dig into it and see what I can find! Thanks for helping to hone in on this issue @daverclarke !

**Comment by mstenta** [comment] 2017-05-18 14:57
Ah... ok, actually... I CAN replicate this on Farmier-hosted sites too. But I can also see how to avoid it...

Here is what's happening: when you are editing a map, notice that you can zoom all the way out to see the whole earth, and if you scroll the map to the right, it repeats (wraps around so you see the same continents passing over and over again).  If you do this a few times, and then draw a shape (anywhere) - the longitude is huge - and the more you scroll the bigger it gets.

So it seems that the map library has a bug where the longitude doesn't reset as you scroll across the map - it just keeps getting bigger and bigger. This is not a bug in farmOS itself - it is either a bug in the Openlayers javascript library (openlayers.org) or the Openlayers Drupal module (https://www.drupal.org/project/openlayers).

I will do some more investigating outside of farmOS to see if I can isolate exactly what piece of software is responsible for this issue. It may also be a known-issue that was already fixed. farmOS uses an older version of the Openlayers javascript library (because there were some issues with the newer one) - so maybe we can find and patch this specific issue, if a fix already exists.

**Comment by mstenta** [comment] 2017-05-18 15:39
OK yup - I found this issue reported in the Openlayers Github issue queue: https://github.com/openlayers/openlayers/issues/3899

**Comment by mstenta** [comment] 2017-06-21 19:15
I'm going to close this issue since it is actually an issue in the Openlayers Javascript library. Thanks @daverclarke for helping to isolate it.

**Comment by mstenta** [comment] 2017-08-10 11:41
I'm reopening this because I've had a few people report similar issues caused by the same underlying OL bug (https://github.com/openlayers/openlayers/issues/3899).

This isn't a farmOS bug, but it is a farmOS problem - so let's leave this open until it's either fixed in OL, or we find a workaround that can be included in farmOS itself.

**Comment by mstenta** [comment] 2017-08-10 13:39
I wrote a PHP script that will automatically fix all longitudes in farmOS, in case anyone runs into this issue and already has a lot of geometries entered.

**BACKUP YOUR SITE BEFORE TRYING THIS!!!**

Here is the script: https://gist.github.com/mstenta/c1393a79776c7a7feb2ff8e650e34216

There are two ways to run it:

**1. With the Devel module**

Go to /devel/php, and paste the whole script in (but remove the first line: `<?php`), and click "Execute".

**2. Using Drush**

Save the script to a file named `fix_longitudes.php` in your webroot and run the following Drush command:

    drush php-script fix_longitudes.php

......

If you use this, please comment and let me know if it works, or if you experience issues. I only tested it on a small site with a few geometries. Be sure to look at a lot of your geometries to make sure they were correctly altered.

**Comment by mstenta** [comment] 2019-11-09 14:32
I created an issue in the new farmOS-map.js library to fix this: https://github.com/farmOS/farmOS-map/issues/49

farmOS will begin using that library in the near future: https://www.drupal.org/project/farm/issues/3083352

Closing this in favor of that.

**Closed as completed by mstenta** 2019-11-09 14:32 UTC
