### ISSUE TITLE
Update Default CSV importers with custom baseFieldDefinition

### ISSUE THREAD

**Issue by Fosten** [farmOS/farmOS#812] opened 2024-03-27 02:01 UTC
When adding a custom bundleFieldDefinition, the CSV Importers automagically pull in the new field.
example: https://github.com/Fosten/farm_seed_asset_extended/blob/main/farm_seed_asset_extended.module
<img width="1096" alt="Screen Shot 2024-03-26 at 9 18 02 PM" src="https://github.com/farmOS/farmOS/assets/1520484/d83f0aad-b92e-47f6-9f23-3067625c525d">

When adding a custom baseFieldDefinition, the CSV importers do not pull in the new field.
example 1:
https://github.com/farmOS/farmOS/blob/3.x/modules/asset/group/farm_group.module
https://github.com/farmOS/farmOS/blob/3.x/modules/asset/group/farm_group.base_fields.inc
example 2: 
https://github.com/Farmer-Eds-Shed/farm_calendar_events/blob/main/farm_calendar_events.module
<img width="1099" alt="Screen Shot 2024-03-26 at 9 19 22 PM" src="https://github.com/farmOS/farmOS/assets/1520484/990d269b-285f-4351-8e69-a7ec9db75932">

**Expected Behavior**
“is_group_assignment” shouldn’t show up because boolean is not yet supported.
But “group” is entity_reference and “calendar” is list_string which are supported.

**Issue**
The difference seems to be bundleFieldDefinition and baseFieldDefinition.

**Comment by paul121** [comment] 2024-03-27 05:38
> The difference seems to be bundleFieldDefinition and baseFieldDefinition.

Yeah this seems to be the case, we're only loading bundle fields here. But I'm not sure where some of the other common asset/log base fields (`name`, `status`, `notes`) are being loaded from...

https://github.com/farmOS/farmOS/blob/0156283a6361e9c59aa357008fde8b478b3ab09b/modules/core/import/modules/csv/src/Plugin/Derivative/CsvImportMigrationBase.php#L123-L130

**Comment by mstenta** [comment] 2024-03-27 08:43
> Yeah this seems to be the case, we're only loading bundle fields here.

Yep - @paul121 linked to the correct bit of code that's responsible for automatically adding bundle fields for "supported" field types:

https://github.com/farmOS/farmOS/blob/0156283a6361e9c59aa357008fde8b478b3ab09b/modules/core/import/modules/csv/src/Plugin/Derivative/CsvImportMigrationBase.php#L155-L160

> But I'm not sure where some of the other common asset/log base fields (`name`, `status`, `notes`) are being loaded from...

The "core" base field mappings for assets, logs, and terms are defined in the `migration/*.yml` files:

https://github.com/farmOS/farmOS/tree/3.x/modules/core/import/modules/csv/migrations

These only include fields that we know for sure will exist on those entity types ("common core base fields" we can call them).

> But “group” is entity_reference and “calendar” is list_string which are supported.

The reason `group` is not included in `migrations/csv_log.yml` is because we can't be sure that the `farm_group` module is enabled. That module is core, but it is optional. And the `group` field it provides is a base field, not a bundle field. 

https://github.com/farmOS/farmOS/blob/0156283a6361e9c59aa357008fde8b478b3ab09b/modules/asset/group/farm_group.base_fields.inc#L13-L33

**Potential next steps:**

We could add some logic to the CSV import module that automatically detects and adds support for base fields, alongside the existing logic for bundle fields. This would pick up `group`. I would be curious what other fields that might end up adding too.

**Comment by mstenta** [comment] 2024-03-27 08:46
Removing the "bug" label, since this is working as expected, but we can consider a next step of auto-detecting base fields.

**Comment by mstenta** [comment] 2024-03-27 09:00
I suppose we can actually close this ("works as designed") and open a PR with actual code changes if/when that next step gets implemented.

I've come to prefer using the farmOS core GitHub issue queue for bug reports primarily, but not for "todos". The forum is the best place for feature requests (and general questions/discussions) IMO, w/ PRs for actual/proposed changes. We also have historically used the drupal.org issue queue for feature discussions (pre-dating the forum), but now I tend to use that more for larger architectural todos. Issue organization is a work in progress. :shrug:

**Closed as not planned by mstenta** 2024-03-27 09:00 UTC
Labels: question

**Comment by Fosten** [comment] 2024-03-27 13:57
Custom CSV Importers work great for bundles, but for modules that implement a new baseField, you'd have to build multiple CSV importers for every Asset/Log Type, just to add one common baseField.

With the only difference being:
  type:
    plugin: default_value
    default_value: seed
  type:
    plugin: default_value
    default_value: animal
etc.

This would appear to be the main benefit in having the default CSV Importers pull in custom baseFields automagically.  If upon module install/uninstall baseFields were recognized as additions/subtractions to the "common core base fields" similar to how additions/subtractions to the "common core bundle fields" work.

Thanks for taking a look at this!
