### ISSUE TITLE
Log Type request: Death

### ISSUE THREAD

**Issue by Skipper-is** [farmOS/farmOS#197] opened 2019-08-21 09:04 UTC
We can log birth, movements and sales, but  I can't find an obvious way of recording deaths. Would we be able to get a deaths category? I did have a go at making a new log type, but it wasn't as straight forward as I had hoped...

**Comment by mstenta** [comment] 2019-08-22 15:31
Chatted with @Skipper-is about this earlier... transcript for posterity:

[09:05:10] | <mstenta[m]> | So basically the thought is: we need a more explicit way of defining the life span of an asset
-- | -- | --
[09:05:35] | <mstenta[m]> | So that assets can have a specific start and end
[09:05:50] | <mstenta[m]> | We can already sort of represent this
[09:05:55] | <mstenta[m]> | But it's more implicit
[09:06:54] | <mstenta[m]> | I  have thought about adding a Death log... But ultimately I think it  might be better to allow *any* kind of log to represent an asset's end
[09:07:08] | <mstenta[m]> | Eg: a harvest log
[09:07:09] | <skipper_is[m]1> | Archiving kind of works
[09:07:29] | <mstenta[m]> | Or a sale log
[09:07:43] | <skipper_is[m]1> | Ok, but for stock it would be good to have something explicit for ones that just died on holding
[09:08:12] | <skipper_is[m]1> | Sale log works if they are sold, but it might've just drowned in a ditch...
[09:08:12] | <mstenta[m]> | Yes,  archiving is sort of the implicit way right now, and previously it was  actually "active" vs "inactive" but I changed it to archived as a first  step towards being more explicit
[09:08:24] | <mstenta[m]> | Right, and that could be an observation
[09:08:45] | <mstenta[m]> | Or an activity, if you don't consider it a harvest or an accident
[09:08:48] | <mstenta[m]> | So:
[09:08:58] | <mstenta[m]> | What I've been thinking about doing is...
[09:09:19] | <mstenta[m]> | Adding a flexible concept of "property changes" that can be associated with logs
[09:09:28] | <skipper_is[m]1> | Like movements?
[09:09:29] | <mstenta[m]> | Similar to the way movements/location work
[09:09:33] | <mstenta[m]> | Yes!
[09:09:34] | <skipper_is[m]1> | Ok
[09:09:49] | <skipper_is[m]1> | But the location is the land where the grass is always green and the sun always shines
[09:10:10] | <mstenta[m]> | So when you create a log, you could optionally set an asset's property at that time
[09:10:51] | <mstenta[m]> | And one of the properties could be "inactive" or "dead" or something like that
[09:11:06] | <mstenta[m]> | And similarly, we could use birth logs to set the birthdate
[09:14:43] | <mstenta[m]> | In the meantime, the way I record "deaths" is simply: add a log (eg: harvest or observation), and then archive the asset
[09:47:34] | <skipper_is[m]1> | Yea, and maybe a category"death" so they can be listed
[10:15:31] | <mstenta[m]> | yea not a bad idea

**Comment by mstenta** [comment] 2019-08-22 15:32
Here is the official issue for implementing the asset lifespan idea via logs: https://www.drupal.org/project/farm/issues/2630218

Closing this as a duplicate of that.

**Closed as completed by mstenta** 2019-08-22 15:32 UTC
Labels: duplicate
