### ISSUE TITLE
Farm areas error

### ISSUE THREAD

**Issue by komatek21** [farmOS/farmOS#242] opened 2020-02-06 13:33 UTC
Trying to draw a farm area and the returned page is:
``Error
The website encountered an unexpected error. Please try again later.``

Findings in /admin/reports/dblog:

````
Type | php
Thursday, February 6, 2020 - 13:00

Location:  https://www.xxx.xxx/admin/structure/taxonomy/farm_areas/add?destination=farm
Referrer:   https://www.xxx.xxx/admin/structure/taxonomy/farm_areas/add?destination=farm
Message:   Error: Call to a member function getY() on null in Polygon->area() (line 32 of /var/www/xxx.xxx/profiles/farm/modules/contrib/geophp/geoPHP/lib/geometry/Polygon.class.php).
Severity:   error
````

````

Type    php
Thursday, February 6, 2020 - 13:00

Location:  https://www.xxx.xxx/admin/structure/taxonomy/farm_areas/add?destination=farm
Referrer:   https://www.xxx.xxx/admin/structure/taxonomy/farm_areas/add?destination=farm
Message:   Notice: Undefined index: 1.000000000000000000000000 in Polygon->area() (line 32 of /var/www/xxx.xxx/profiles/farm/modules/contrib/geophp/geoPHP/lib/geometry/Polygon.class.php).
Severity:   notice
````

**Comment by mstenta** [comment] 2020-02-06 15:57
Ah ha! Thanks for making a GitHub issue for this @komatek21, after bringing it up in chat. Now that I see the error message I recognize it as a bug that was fixed recently!

The fix will be included in the next release of farmOS, but in the meantime you can also fix it manually relatively easily. See https://www.drupal.org/project/geophp/issues/3050510#comment-13407879

**Comment by mstenta** [comment] 2020-02-06 16:00
Closing this as a duplicate of this previous issue: https://github.com/farmOS/farmOS/issues/161 (I will also update that one to link to the fix described above).

**Closed as completed by mstenta** 2020-02-06 16:00 UTC
Labels: duplicate
