### ISSUE TITLE
Can we add Movement to Seeding and Transplanting Log Importers?

### ISSUE THREAD

**Issue by megandalster** [farmOS/farmOS#306] opened 2020-06-05 21:47 UTC
Seeding and Transplanting Logs have Movement (Area and Geometry) field collections, but their importers do not have a Movement column.  So bulk imports of Seeding and Transplanting Logs from other databases cannot currently capture this valuable information.

This issue stems from a longer discussion I've been having with @mstenta in issue #199, where I have been slowly migrating a substantial FarmData database over to a new FarmOS platform.  Until this issue is fixed, I cannot import ~5 years of seeding and transplanting logs from that database, since each log carries valuable Area data.

@mstenta has given me a lot of good advice along the way, but now my unfamiliarity with modifying feeds importers in Drupal is keeping me from moving forward.  For more background on this issue and the more general challenges I've encountered with FarmData --> FarmOS migration, see issue #199.

Also, if there are other FarmData users out there with similar interests or questions, maybe we could start a working group to share our experiences?  Sheltering in place on this bigger challenge is getting lonely :-)

Thanks in advance!

**Comment by mstenta** [comment] 2020-06-10 12:14
@megandalster Here is the original feature request I created for this a while back: https://www.drupal.org/project/farm/issues/2918234

It is a bit more general and covers group membership and inventory adjustments, in addition to movements.  But starting with movements would be a good first step, I agree.  That is the most commonly needed one.

I'm going to close this as a duplicate of that, but I will add a comment linking back to here for reference.

**Closed as completed by mstenta** 2020-06-10 12:14 UTC
Labels: duplicate, question
