### ISSUE TITLE
Error with "show dashboard maps"

### ISSUE THREAD

**Issue by ykir90** [farmOS/farmOS#133] opened 2019-01-30 12:36 UTC
I have a problem with a new installation of FarmOS, version 7.x-1.0-rc2
Practically when I want to access the AREAS card I see this error:

 Fatal error: Declaration of Drupal\farm_map\Plugin\Control\OLGeocoder\OLGeocoder::preBuild(array &$build, ?Drupal\openlayers\Types\BaseInterface $context = NULL) must be compatible with Drupal\openlayers\Types\ObjectInterface::preBuild(array &$build, ?Drupal\openlayers\Types\ObjectInterface $context = NULL) in /web/htdocs/www.####.com/home/profiles/farm/modules/farm/farm_map/src/Plugin/Control/OLGeocoder/OLGeocoder.php online 34

Disabling the option "Show dashboard maps" the error does not appear and the page works without of course seeing the map.

I don't use Goggle Api Key.

It's not completely clear to me if I can display a map with Openstreetmap on that page without using Google's Key API and so I don't really know if it's the lack of the latter that generates the error.

I thank in advance for the help and congratulations for the great work.

Riccardo

**Comment by mstenta** [comment] 2019-01-30 12:47
Hi Riccardo,

What version of PHP are you using?  And did you change/update any of the code/modules that come with farmOS?

The error you're seeing is coming from the OpenLayers module. It is related to the fact that the current "stable" release of the Openlayers Drupal module does not support PHP 7. farmOS includes a patch to this module which fixes this issue.  With that in mind, my guess is that you are not using the correct version, or you are missing the required patch that adds support for PHP 7.

If you downloaded farmOS from https://drupal.org/project/farm, it will include the correct versions of all modules, along with their necessary patches. It is not recommended that you update modules individually, unless you know what patches are required (if any) and how to apply them. See https://farmos.org/hosting/updating/

If you do not have any data in your farmOS site, I would recommend installing it again from scratch and using the code as-is from https://drupal.org/project/farm

**Comment by mstenta** [comment] 2019-01-30 12:52
I'm going to close this issue since i'm 99% confident that's what the issue is (I dealt with that issue a fair bit while testing and upgrading farmOS to work with PHP 7). But if you think that's wrong, let me know and we can reopen it.

We can still use this issue to help you get straightened out, even though it's "closed". :-)

**Closed as completed by mstenta** 2019-01-30 12:52 UTC

**Comment by ykir90** [comment] 2019-01-30 12:58
The version of PHP is 7.1.11, ok I missed this step and being a simple farmer I prefer to reinstall everything with version php 5.6.32 rather than try to apply patches that I combine only messes.
Thanks a lot!

**Comment by mstenta** [comment] 2019-01-30 13:45
@ykir90 No! Stay on PHP 7.1.11! You're on the right track! :-)

You don't need to apply any patches. farmOS 7.x-1.0-rc2 should work on PHP 7.1.11 (as far as I know).

Can you help me understand how you installed farmOS? Did you simply download the packaged tar.gz or zip file from https://drupal.org/project/farm? Did you make any modifications to that code or try to update any modules after you downloaded it?

**Comment by ykir90** [comment] 2019-01-31 17:09
I found that the version of openlayer on the server was different from the one contained in the version I had uploaded, which was the one in the distro farmOS that I uploaded as is from the site https://drupal.org/project/farm , so most likely I had updated some module or something like that, now I deleted everything and reloaded farmOS, I'm installing it now, should that error reappear I let you know

**Comment by ykir90** [comment] 2019-01-31 17:11
it is very likely that I have made some mess I, as I repeat I am a farmer :)

I'm installing with php in version 7.1.11 as you advised me @mstenta

**Comment by mstenta** [comment] 2019-01-31 17:22
Ah great - yea that would explain it.

> it is very likely that I have made some mess I, as I repeat I am a farmer :)

Haha that's half the fun, isn't it? And the best way to learn something new. :-)

**Comment by ykir90** [comment] 2019-01-31 17:33
It's all right, it's working perfectly, my mistake.

Thank you very much

**Comment by mstenta** [comment] 2019-01-31 17:35
Great!
