### ISSUE TITLE
Missing translation of log and asset menu

### ISSUE THREAD

**Issue by bitfieldfarm** [farmOS/farmOS#626] opened 2023-01-11 07:33 UTC
**Log and asset type names are not translated.**

According to this issue https://www.drupal.org/project/farm/issues/3262752 it seems fixed, but it's not.

Also discussed here
https://farmos.discourse.group/t/farmos-translating-problem/1084

If I add a module, the menus are translated correctly. But at some time the translation is lost again. Don't know yet what triggers that.

**Comment by mstenta** [comment] 2023-01-11 14:20
Hmm I wonder if this is a regression, or if it is a different set of menu items than the ones we fixed before.

Can you take some screenshots so I can see exactly which menus you're referring to?

Thanks for opening this @bitfieldfarm!

**Comment by bitfieldfarm** [comment] 2023-01-11 15:54
![bilde](https://user-images.githubusercontent.com/98184919/211852513-bff4cfc9-8d67-4439-bb18-85ae00f15529.png)

Also the dashboard:
![bilde](https://user-images.githubusercontent.com/98184919/211852754-6f3b0248-0a65-48a1-bf96-0a9ac18f8ab7.png)

**Comment by mstenta** [comment] 2023-01-16 19:22
Bah! It does sound like the same issue I already "fixed". :-(

I re-read the old threads around that issue (which you linked to above), and while they have a lot of good detail about the problem, I'm not sure if I ever figured out why clearing caches vs installing modules made a difference...

> The other open question is: why does installing/uninstalling a module cause the bundle labels to be translated already when we are constructing menu links? [.....] but it seems strange that this would behave differently during cache clear vs during module (un)install... but maybe that's a separate issue entirely, [....]

https://www.drupal.org/project/farm/issues/3262752#comment-14400258

**Comment by mstenta** [comment] 2023-01-16 19:24
@bitfieldfarm just to confirm: you said this seems to have been fixed when you installed a module, correct? But then seems to randomly break again at some point after that?

> If I add a module, the menus are translated correctly. But at some time the translation is lost again.

It could be that the "random" break happens when a normal background operation of some kind happens. eg: cron is run, or caches are cleared. I perform routine upgrades of Farmier-hosted instances, and that generally involves a cache clear and update.php.

**Comment by bitfieldfarm** [comment] 2023-01-16 20:57
Yea. That's correct. Install a module "activates" the translation.

Could you give me a notice when this happens? And I will check more carefully.

**Comment by bitfieldfarm** [comment] 2023-01-20 14:42
@mstenta Huh.. today my menu had lost it's translation.
The dashboard items are stil translated.

Did'nt do anything special in farmOS. Only regular logging.

**Comment by mstenta** [comment] 2023-01-20 14:54
Ok that makes sense @bitfieldfarm because I rolled out an update to Farmier instances 2 days ago. That probably did it (via cache clear or whatever).

So I think we need to figure out why that's happening... that's the bug. And it would be a bug in farmOS/Drupal, not Farmier, because we must be able to assume that anyone hosting farmOS will be clearing the cache etc.

I'll try to set aside some time to debug this soon...

**Comment by mstenta** [comment] 2023-01-20 16:49
This seems similar: https://www.drupal.org/project/drupal/issues/2650434

**Comment by mstenta** [comment] 2023-01-22 15:04
I am able to replicate this locally. It happens when the cache is cleared via Drush. It also happens when the cache is cleared via the UI, but notably this depends on what language the user who clears the cache is using. If the user is using the default language (English), then it breaks menu translations for all users with non-default languages. If, however, the user is using the non-default language when they clear the cache, it "fixes" the translations for other non-default language users (I say "fixes" because I haven't tested this with multiple non-default languages... it may break things for other languages). This indicates to me that it's a cache pollution issue... where the language of the user who is rebuilding the cache is what gets used. When `drush cr` is used, there isn't a user, so it's using English (the default) - that's my assumption.

I found these Drupal core issues that also sound similar:

- https://www.drupal.org/project/drupal/issues/3114824
- https://www.drupal.org/project/drupal/issues/3221375

I tried the patch (from comment 9) in the first one, but that didn't seem to make a difference.

, or via the UI as admin user with default language. Notably, if a user with the non-default language clears the cache via the UI, it does not cause the issue.

**Comment by mstenta** [comment] 2023-01-22 15:11
This sounds like a pretty accurate description of what's happening - although I haven't confirmed if it's exactly the same as what we're seeing: https://www.drupal.org/project/drupal/issues/2189267#comment-14427405

**Comment by mstenta** [comment] 2023-01-22 15:18
I also tried this patch and it did not help: https://www.drupal.org/project/drupal/issues/3221375#comment-14231642

**Comment by mstenta** [comment] 2023-01-22 15:22
> If, however, the user is using the non-default language when they clear the cache, it "fixes" the translations for other non-default language users (I say "fixes" because I haven't tested this with multiple non-default languages...

Ha! I just confirmed (by enabling both German and Norwegian translations) that a German user clearing the cache causes a Norwegian user to see German translations in the menu. :facepalm:

**Comment by mstenta** [comment] 2023-01-22 15:37
> a German user clearing the cache causes a Norwegian user to see German translations in the menu

Just to clarify this... it isn't ALL menu items that are incorrect. It is only the asset/log type names.

This gives us a good place to start debugging... since those are generated by our module.

**Comment by mstenta** [comment] 2023-01-22 16:32
Ah hmm... so actually it looks like https://www.drupal.org/project/farm/issues/3262752 was NOT actually fixed as expected... our menu link titles are still being returned as plain text, rather than `TranslatableMarkup` objects, despite using `$bundle->label()`.

To be continued...

**Comment by mstenta** [comment] 2023-01-23 13:26
I reopened https://www.drupal.org/project/farm/issues/3262752 - I'm going to close this thread and continue over there...

**Closed as not planned by mstenta** 2023-01-23 13:26 UTC
Labels: bug

**Comment by mstenta** [comment] 2023-02-08 21:41
@bitfieldfarm Just wanted to let you know: I plan to apply a "hotfix" for this in Farmier instances specifically, so it should be resolved for you soon! That should relieve the frustration it causes while we wait for a "proper" fix.

**Comment by bitfieldfarm** [comment] 2023-02-09 10:37
Thats cool. Thanks.
